### ISSUE TITLE
opy obfuscates python's keywords

### ISSUE THREAD

**Issue by andimarafioti** [QQuick/Opy#15] opened 2017-01-02 19:26 UTC
I found opy will obfuscate some keywords like "open".

**Comment by andimarafioti** [comment] 2017-01-02 19:57
This bug happens on my local branch of opy because of the changes I mentioned in https://github.com/QQuick/Opy/issues/14 . It doesn't happen if I undo those changes.

**Comment by JdeH** [comment] 2017-01-04 18:49
Alright, I wouldn't know a solution for now.
Except for exempting words like 'open' explicitly in the config file...

**Comment by andimarafioti** [comment] 2017-01-04 18:54
For what is worth, I tried exempting every python keyword in the config file but it didn't work.

**Comment by JdeH** [comment] 2017-01-04 19:04
Well, that's not as it should be... So I'll reopen this one as well.

**Comment by JdeH** [comment] 2017-01-04 19:16
I've tried to reproduce the exempting as with the following config:

```
#====================================================================================================
# Extra identifiers and module names (as opposed to contents) that should not be obfuscated
# Probably at least the names of your main modules (so not their filenames) go here
#====================================================================================================

plain_names = '''
opy
currentModule
blabla
'''
```

It indeed leaves 'blabla' unobfuscated:

```
# coding: UTF-8
from __future__ import absolute_import
import sys
l1llll111_opy_ = sys.version_info [0] == 2
l1l1l111_opy_ = 2048
l111111l_opy_ = 7
def l11ll_opy_ (l11111_opy_):
    global l1l1l1ll_opy_
    l11ll1l1_opy_ = ord (l11111_opy_ [-1])
    l1llll11l_opy_ = l11111_opy_ [:-1]
    l1lll1ll_opy_ = l11ll1l1_opy_ % len (l1llll11l_opy_)
    l1ll1ll_opy_ = l1llll11l_opy_ [:l1lll1ll_opy_] + l1llll11l_opy_ [l1lll1ll_opy_:]
    if l1llll111_opy_:
        l1l1ll_opy_ = unicode () .join ([unichr (ord (char) - l1l1l111_opy_ - (l1ll11l1_opy_ + l11ll1l1_opy_) % l111111l_opy_) for l1ll11l1_opy_, char in enumerate (l1ll1ll_opy_)])
    else:
        l1l1ll_opy_ = str () .join ([chr (ord (char) - l1l1l111_opy_ - (l1ll11l1_opy_ + l11ll1l1_opy_) % l111111l_opy_) for l1ll11l1_opy_, char in enumerate (l1ll1ll_opy_)])
    return eval (l1l1ll_opy_)
import string
string.l1ll1111l_opy_ ()
print (l11ll_opy_ (u"࠭࠱ࠤ࠴ࠦ࠷ࠬࡤ"))
blabla = 3
print (blabla)

```

So I cannot reproduce the exempting not working. Are you sure you added 'open' etc. in the right section?

**Comment by JdeH** [comment] 2017-01-04 19:22
Since this seems to be something specific with keywords, rather than exempting words in general, like 'blabla', I'll close this one and refer to #14.

**Closed by JdeH** 2017-01-04 19:22 UTC
