### ISSUE TITLE
When debugging opy.py the "addExternalNames" functions hangs the execution

### ISSUE THREAD

**Issue by andimarafioti** [QQuick/Opy#14] opened 2016-12-30 16:04 UTC
I'm using the latest version of Pycharm and I'm getting this error when I debug opy.py:

`C:/Users/Dev5/Documents/myProject/opy.py:360: RuntimeWarning: tp_compare didn't return -1 or -2 for exception`

For some reason, this hangs the execution. The error comes from the check:

    if anObject in externalObjects:
        return

in the addExternalNames function. A simple way to fix this is to check in the function if the argument is Hashable. If it is not, then it shouldn't be in externalObjects so I return.

    def addExternalNames(anObject):
        if isinstance(anObject, collections.Hashable):
            return
        if anObject in externalObjects:
            return

I don't know why this bug exists though and this is simply a patch to avoid something that shouldn't happen in the first place.

**Comment by JdeH** [comment] 2017-01-04 18:48
Hi,

No idea why this occurs.
If I look at #15, it seems like the patch won't work, so I'll close it for now.
Feel free to reopen if I misunderstood.

Kind regards
Jacques

**Comment by andimarafioti** [comment] 2017-01-04 18:53
Hi,

I think this issue should be open because there is no obvious fix (see https://github.com/QQuick/Opy/issues/15). 
Can you debug the execution correctly? I tested it in two machines but they have a pretty similar configuration. 
I agree https://github.com/QQuick/Opy/issues/15 should be closed as that issue only comes from the quick fix I proposed here.

Regards
Andres

**Comment by JdeH** [comment] 2017-06-27 13:27
Really seems to be a debugger thing.
Can't reproduce it on the command line.
So I'll once again close it.
If anyone can reproduce it outside the debugger, feel free to reopen.

**Closed by JdeH** 2017-06-27 13:27 UTC

**Comment by vkhazin** [comment] 2020-07-29 03:43
I am facing the issue outside of debugger running on Windows 10 64bit from PowerShell, had to kill the process externally:
https://github.com/vkhazin/python-obfuscate/blob/master/package.ps1#L24
